version: '3.8'
services:
  db:
    image: mysql:8.0
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jtk_berbagi_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: rails123
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
  server:
    # build: ./service
    build: arn4n/jtk-berbagi-server:latest
    # command: bundle exec puma -C config/puma.rb
    # volumes:
    #   - ./service:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=rails
      - MYSQL_PASSWORD=rails123
      - MYSQL_DATABASE=jtk_berbagi_development
    entrypoint: ["sh", "./entrypoint.sh"]
  client:
    build: arn4n/jtk-berbagi-client:latest
    # volumes:
    #   - ./client:/app
    #   - /app/node_modules
    ports:
      - '3000:3000'
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
volumes:
  db_data:
